# PostgreSQL. Versions 8.2 and up are supported.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: editor_development

test:
  <<: *default
  database: editor_test

production:
  <<: *default
  database: editor_production
  username: editor
  password: <%= ENV['STORE-KEEPER_DATABASE_PASSWORD'] %>
